version: '3'

services:
  php:
    container_name: online_store
    build:
      context: .
      dockerfile: ./docker/Dockerfile-dev
    volumes:
      - ./:/var/www
      - ./var/log:/var/log
    ports:
      - "8001:80"

  db:
    container_name: online_store_db
    image: mariadb:10.7.4
    restart: always
    environment:
      - MYSQL_DATABASE=online_store
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db_local:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "--user=root", "--password=", "--host=127.0.0.1", "ping", "--silent" ]
      interval: 2s
      timeout: 10s
      retries: 10
    command: [ "--default-authentication-plugin=mysql_native_password" ]

volumes:
  db_local: